
package image;
public enum Image {
LIFE,WIN,GAMEOVER ,SHOTS, SCORE, BRICKBREAKER,NEXTLEVEL,
RED_GIFT,SHOT_GUN,GREEN_GIFT,PADDLE_EXPAND,BLUE_GIFT,
//level 1,2
BALL1,PADDLE1,BRICK1,BACKGROUND1,
//level 3, 4
BACKGROUND2,BALL2,PADDLE2,BRICK2,
//level monster
MONSTER,BACKGROUND3,BALL3;
}
